FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80


FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src

RUN apt update && apt upgrade -y


COPY . .
WORKDIR "/src/Api"
ENV ConnectionStringDb="Server=.\\SQLEXPRESS; Database=CrudTestWeb;Trusted_Connection=SSPI;MultipleActiveResultSets=true;Trust Server Certificate=true"


RUN dotnet build "CrudTestWeb.WebApi.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "CrudTestWeb.WebApi.csproj" -c Release -o /app

FROM base AS final
WORKDIR /
ENV TZ=America/Bogota
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN date

WORKDIR /app
RUN apt-get update

COPY --from=publish /app .

ENTRYPOINT ["dotnet", "CrudTestWeb.WebApi.dll"]
