FROM node:18 as build
RUN apt update && apt upgrade -y

WORKDIR /usr/local/app

COPY package.json package-lock.json /usr/local/app/
RUN npm install
COPY . /usr/local/app/
RUN npm run build

FROM nginx:latest

COPY --from=build /usr/local/app/dist/web-front /usr/share/nginx/html

COPY ./nginx.conf /etc/nginx/conf.d/default.conf
CMD ["nginx", "-g", "daemon off;"]
